quests:
  - id: "missing_miner"
    title: "MISSING PERSON - REWARD OFFERED"
    description: "Tomek the Miner has been missing for three days. Last seen heading toward the old silver mine entrance. Young man, brown hair, wearing mining clothes. His family is desperate for news."
    contact: "Bartek at the Tawny Lion Inn"
    reward_gold: 50
    reward_exp: 100
    type: "urgent"
    requirements: []
    completion_requirements:
      - "talk_to_bartek"
      - "investigate_mine"
    completed_by: []
    steps:
      - action: "talk_to_bartek"
        location: "tavern"
        description: "Talk to Bartek about missing Tomek"
        completed: false
      - action: "investigate_mine"
        location: "mine_entrance"
        description: "Search the mine entrance for clues"
        completed: false
  - id: "mine_sounds"
    title: "STRANGE SOUNDS FROM THE MINE"
    description: "Villagers report hearing unnatural sounds echoing from the abandoned silver mine at night. Brave souls wanted to investigate. Extreme caution advised."
    contact: "Village elders"
    reward_gold: 75
    reward_exp: 150
    type: "urgent"
    requirements:
      - "level >= 2"
    required_items:
      - "torch"
      - "potion_health_small"
    consumes_items:
      - "torch"
    completion_requirements:
      - "investigate_mine_sounds"
    completed_by: []
    steps:
      - action: "buy_materials"
        location: "tradesman"
        description: "Buy a torch and healing potion from Erik"
        required_items:
          - "torch"
          - "potion_health_small"
        completed: false
      - action: "investigate_mine_sounds"
        location: "mine_entrance"
        description: "Investigate the strange sounds at the mine"
        consumes_items:
          - "torch"
        completed: false
